title: The Lilac Libretto
description: An enchanted haven for book recommendations, cozy playlists, and sweet recipes
baseurl: "https://snelso24.github.io/thelilaclibretto/"
url: "https://snelso24.github.io/thelilaclibretto/"

collections:
  baking:
    output: true
  reading:
    output: true
  music:
    output: true

defaults:
  - scope:
      path: ""
      type: "baking"
    values:
      layout: default
  - scope:
      path: ""
      type: "reading"
    values:
      layout: default
  - scope:
      path: ""
      type: "music"
    values:
      layout: default
